Algoritmo "senha fixa"
// Disciplina  : Estruturas de repetição
// Professor   : Nélio Alves
// Aluno       : Henrique Gibi de Pádua
// Data atual  : 06/10/2020
Var
   senha : inteiro

Inicio

   escreva("Digite a senha: ")
   leia(senha)
   
   enquanto senha <> 2002 faca
      escreva("Senha Invalida! Tente novamente: ")
      leia(senha)
   fimenquanto
   
   escreval()
   escreval("Acesso permitido!")

Fimalgoritmo